git_response = {
    "login": "dimddev",
    "id": 57534,
    "node_id": "MdQ6VXnlc4U3NTM0NDA=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/5753440?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dimddev",
    "html_url": "https://github.com/dimddev",
    "followers_url": "https://api.github.com/users/dimddev/followers",
    "following_url":
        "https://api.github.com/users/dimddev/following{/other_user}",
    "gists_url": "https://api.github.com/users/dimddev/gists{/gist_id}",
    "starred_url":
        "https://api.github.com/users/dimddev/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dimddev/subscriptions",
    "organizations_url": "https://api.github.com/users/dimddev/orgs",
    "repos_url": "https://api.github.com/users/dimddev/repos",
    "events_url": "https://api.github.com/users/dimddev/events{/privacy}",
    "received_events_url":
        "https://api.github.com/users/dimddev/received_events",
    "type": "User",
    "site_admin": "false",
    "name": "Di Mita Hakini",
    "company": "null",
    "blog": "http://nasa.gov",
    "location": "Sofia",
    "email": "targolini@gmail.com",
    "hireable": "null",
    "bio": "null",
    "public_repos": 34,
    "public_gists": 2,
    "followers": 21,
    "following": 12,
    "created_at": "2013-10-23T06:07:30Z",
    "updated_at": "2019-08-24T09:06:41Z",
    "private_gists": 1,
    "total_private_repos": 0,
    "owned_private_repos": 0,
    "disk_usage": 5819,
    "collaborators": 0,
    "two_factor_authentication": "false",
    "plan":
        {
            "name": "free",
            "space": 976562499,
            "collaborators": 0,
            "private_repos": 10000
        }
}

fresh_response = {
    "active": 'false',
    "address": "Sofia",
    "company_id": 'null',
    "view_all_tickets": 'null',
    "deleted": 'false',
    "description": 'null',
    "email": "dmhakini1012@gmail.com",
    "id": 47003672837,
    "job_title": 'null',
    "language": "en",
    "mobile": 'null',
    "name": "Di Mita Hakini",
    "phone": 'null',
    "time_zone": "Baghdad",
    "twitter_id": 'null',
    "custom_fields": {},
    "tags": [],
    "other_emails": [],
    "facebook_id": 'null',
    "created_at": "2019-09-30T14:05:52Z",
    "updated_at": "2019-09-30T14:05:52Z",
    "other_companies": [],
    "unique_external_id": 'null',
    "avatar": 'null'
}
